var exerciseScript = {
        $('#spark').hide();
        $('#clickme').hide();
        $('#math').hide();
        $('#sweet').hide();
        $('#perceptron1').hide();
        $('#perceptron2').hide();
        $('#perceptron3').hide();
        $('#perceptron4').hide();
        $('#perceptron5').hide();
        $('#hoveroverme').hide();
        $('#hovered').hide();
        $('#question1').hide();
        $('#question2').hide();
        $('#question3').hide();
        $('#weight1').hide();
        $('#weight2').hide();
        $('#weight3').hide();
        $('#answers').hide();
        $('#decision').hide();
        $('#decision2').hide();
        $('#videoCanvas').hide();
        $('#neuralForm').fadeIn();
        $('#go').fadeIn();
        $('#dontgo').fadeIn();
}
